const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } = require('docx');
const auth = require('../middleware/auth');
const Meeting = require('../models/Meeting');

// Export as PDF
router.get('/:id/pdf', auth, async (req, res) => {
  try {
    const meeting = await Meeting.findOne({ _id: req.params.id, user: req.user._id });
    if (!meeting) return res.status(404).json({ success: false, message: 'Meeting not found' });

    const doc = new PDFDocument({ margin: 50, size: 'A4', bufferPages: true });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${meeting.title.replace(/[^a-z0-9]/gi, '_')}.pdf"`);
    doc.pipe(res);

    // Header
    doc.fontSize(24).font('Helvetica-Bold').fillColor('#1a1a2e').text('Meeting Notes', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(18).font('Helvetica-Bold').fillColor('#16213e').text(meeting.title, { align: 'center' });
    doc.moveDown(0.3);
    doc.fontSize(11).font('Helvetica').fillColor('#666').text(
      `Date: ${new Date(meeting.createdAt).toLocaleDateString()} | Duration: ${Math.round((meeting.duration || 0) / 60)} min | Words: ${meeting.wordCount || 0}`,
      { align: 'center' }
    );
    doc.moveDown(1);

    // Divider
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e2e8f0').stroke();
    doc.moveDown(1);

    // Summary
    if (meeting.summary?.overview) {
      doc.fontSize(14).font('Helvetica-Bold').fillColor('#1a1a2e').text('Meeting Summary');
      doc.moveDown(0.5);
      doc.fontSize(11).font('Helvetica').fillColor('#374151').text(meeting.summary.overview, { lineGap: 4 });
      doc.moveDown(1);
    }

    // Key Points
    if (meeting.summary?.keyPoints?.length) {
      doc.fontSize(14).font('Helvetica-Bold').fillColor('#1a1a2e').text('Key Discussion Points');
      doc.moveDown(0.5);
      meeting.summary.keyPoints.forEach(point => {
        doc.fontSize(11).font('Helvetica').fillColor('#374151').text(`• ${point}`, { lineGap: 3 });
      });
      doc.moveDown(1);
    }

    // Action Items
    if (meeting.actionItems?.length) {
      doc.fontSize(14).font('Helvetica-Bold').fillColor('#1a1a2e').text('Action Items');
      doc.moveDown(0.5);
      meeting.actionItems.forEach((item, i) => {
        const status = item.completed ? '☑' : '☐';
        const priority = item.priority === 'high' ? '[HIGH]' : item.priority === 'low' ? '[LOW]' : '[MED]';
        const assignee = item.assignee ? ` → ${item.assignee}` : '';
        doc.fontSize(11).font('Helvetica').fillColor('#374151')
          .text(`${status} ${i + 1}. ${item.task}${assignee} ${priority}`, { lineGap: 3 });
      });
      doc.moveDown(1);
    }

    // Participants
    if (meeting.participants?.length) {
      doc.fontSize(14).font('Helvetica-Bold').fillColor('#1a1a2e').text('Participants');
      doc.moveDown(0.5);
      meeting.participants.forEach(p => {
        doc.fontSize(11).font('Helvetica').fillColor('#374151')
          .text(`• ${p.name}${p.role ? ` (${p.role})` : ''}`, { lineGap: 3 });
      });
      doc.moveDown(1);
    }

    // Transcript
    if (meeting.transcript?.full) {
      doc.addPage();
      doc.fontSize(14).font('Helvetica-Bold').fillColor('#1a1a2e').text('Full Transcript');
      doc.moveDown(0.5);
      if (meeting.transcript.segments?.length) {
        meeting.transcript.segments.forEach(seg => {
          doc.fontSize(10).font('Helvetica-Bold').fillColor('#4a5568').text(seg.speaker + ':');
          doc.fontSize(10).font('Helvetica').fillColor('#374151').text(seg.text, { lineGap: 2 });
          doc.moveDown(0.3);
        });
      } else {
        doc.fontSize(10).font('Helvetica').fillColor('#374151').text(meeting.transcript.full, { lineGap: 4 });
      }
    }

    // Footer
    const pageCount = doc.bufferedPageRange().count;
    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i);
      doc.fontSize(9).fillColor('#aaa').text(
        `Generated by AI Meeting Notes • Page ${i + 1} of ${pageCount}`,
        50, doc.page.height - 30, { align: 'center' }
      );
    }

    doc.end();
  } catch (error) {
    console.error("PDF Export Crash:", error);
    res.status(500).json({ success: false, message: error.message, stack: error.stack });
  }
});

// Export as DOCX
router.get('/:id/docx', auth, async (req, res) => {
  try {
    const meeting = await Meeting.findOne({ _id: req.params.id, user: req.user._id });
    if (!meeting) return res.status(404).json({ success: false, message: 'Meeting not found' });

    const children = [
      new Paragraph({ text: 'Meeting Notes', heading: HeadingLevel.TITLE, alignment: AlignmentType.CENTER }),
      new Paragraph({ text: meeting.title, heading: HeadingLevel.HEADING_1, alignment: AlignmentType.CENTER }),
      new Paragraph({
        children: [new TextRun({ text: `Date: ${new Date(meeting.createdAt).toLocaleDateString()} | Duration: ${Math.round((meeting.duration || 0) / 60)} min`, color: '666666', size: 20 })]
      }),
      new Paragraph({ text: '' })
    ];

    if (meeting.summary?.overview) {
      children.push(new Paragraph({ text: 'Meeting Summary', heading: HeadingLevel.HEADING_2 }));
      children.push(new Paragraph({ text: meeting.summary.overview }));
      children.push(new Paragraph({ text: '' }));
    }

    if (meeting.summary?.keyPoints?.length) {
      children.push(new Paragraph({ text: 'Key Discussion Points', heading: HeadingLevel.HEADING_2 }));
      meeting.summary.keyPoints.forEach(point => {
        children.push(new Paragraph({ text: `• ${point}` }));
      });
      children.push(new Paragraph({ text: '' }));
    }

    if (meeting.actionItems?.length) {
      children.push(new Paragraph({ text: 'Action Items', heading: HeadingLevel.HEADING_2 }));
      meeting.actionItems.forEach((item, i) => {
        const status = item.completed ? '☑' : '☐';
        const assignee = item.assignee ? ` → ${item.assignee}` : '';
        children.push(new Paragraph({ text: `${status} ${i + 1}. ${item.task}${assignee} [${item.priority?.toUpperCase()}]` }));
      });
    }

    const doc = new Document({ sections: [{ properties: {}, children }] });
    const buffer = await Packer.toBuffer(doc);

    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    res.setHeader('Content-Disposition', `attachment; filename="${meeting.title.replace(/[^a-z0-9]/gi, '_')}.docx"`);
    res.send(buffer);
  } catch (error) {
    console.error("DOCX Export Crash:", error);
    res.status(500).json({ success: false, message: error.message, stack: error.stack });
  }
});

module.exports = router;
